#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MoneyKeeper.Mobile.Android.Resource", IsApplication=true)]

namespace MoneyKeeper.Mobile.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::MoneyKeeper.Mobile.Android.Resource.String.library_name;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::MoneyKeeper.Mobile.Android.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::MoneyKeeper.Mobile.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int addFinOpDateEditText = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int addFinOpDescriptionEditText = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int addFinOpValueEditText = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int addFinOperationBtn = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int descriptionTextView = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int goToAddFinOperationBtn = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int listView = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int loginBtn = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int loginTextView = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int password = 2131099660;
			
			// aapt resource value: 0x7f060001
			public const int radioExpense = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int radioIncome = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public const int userName = 2131099659;
			
			// aapt resource value: 0x7f060007
			public const int valueTextView = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int view_holder_tag = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddFinOperation = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FinOperationListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FinOperationsList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
